name: example
description: "Demonstrates how to use the fl_recorder plugin."
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_recorder:
    path: ../
  fl_extended: ^2.1.0
  flutter_sound: ^9.28.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
