name: example
description: "Demonstrates how to use the fl_recorder plugin."
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_recorder:
    path: ../
  fl_extended: ^1.9.4
  flutter_sound:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_sound.git
      ref: br_v9.30.0_ohos

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
