name: fl_recorder
description: "Using microphone recording and system audio capture on Flutter."
version: 0.4.0
repository: https://github.com/Wayaer/fl_recorder.git

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  fl_channel: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.recorder
        pluginClass: FlRecorderPlugin
      ios:
        pluginClass: FlRecorderPlugin
      ohos:
        pluginClass: FlRecorderPlugin